name: Deploy DocC to Netlify

on:
  push:
    branches: ["aws"]  # Запуск при пушах у гілку "main"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: macos-15  # Потрібно для використання Xcode

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode and DocC
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Build DocC and Generate Static Site
        run: |
          xcodebuild docbuild -scheme test-doc \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS';

          $(xcrun --find docc) process-archive transform-for-static-hosting \
            /tmp/docbuild/Build/Products/Debug-iphoneos/test-doc.doccarchive \
            --output-path docs \

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Load to S3
        run: aws s3 sync docs s3://${{ secrets.AWS_S3_BUCKET }}/documentation --acl public-read --delete
